### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [WirelessAlien/BhagavadGitaApp#8]
The app/src/main/res/drawable/launcher_icon_light.xml is not in your apk. Removing it fix the build. Is it missed from you build?

**Comment by WirelessAlien** [comment]
> The app/src/main/res/drawable/launcher_icon_light.xml is not in your apk. Removing it fix the build. Is it missed from you build?

Yeah, it is. If I replace the binary in the release by including launcher_icon_light.xml that will solve the issue the right?

Actually, the launcher_icon_light.xml is not necessary, that's why I removed that from Android studio but I didn't push that to git (mistake). I will remove that completely in the next version now I will build the apk by including it.

**Comment by linsui** [comment]
I have remove the file from F-Droid build. It's up to you to rebuild the apk or not.

**Comment by WirelessAlien** [comment]
> I have remove the file from F-Droid build. It's up to you to rebuild the apk or not.

Ooh. Ok. Then I will leave the apk as it is 🙌

**Comment by linsui** [comment]
Ok. :ok_hand:
